spring:
  application:
    name: formula1
  datasource:
    url: jdbc:postgresql://localhost:5432/formula-1
    username: ${DATABASE-USERNAME}
    password: ${DATABASE-PASSWORD}
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: true
formula1-api:
  api-key: ${FORMULA1-KEY}
  base-url: 'https://api-formula-1.p.rapidapi.com'
  host: 'api-formula-1.p.rapidapi.com'
server:
  port: 8085